#!/usr/bin/env bash

set -e

. ./build-scripts/set-path-for-dependencies

# from https://cjycode.com/flutter_rust_bridge/template/setup_web.html
rustup toolchain install nightly
rustup +nightly component add rust-src
rustup +nightly target add wasm32-unknown-unknown

# infered from https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_dart/bin/serve.dart
export RUSTUP_TOOLCHAIN=nightly
export RUSTFLAGS='-C target-feature=+atomics,+bulk-memory,+mutable-globals'

wasm-pack build -t no-modules -d `pwd`/web/pkg --no-typescript --out-name native --dev native -- -Z build-std=std,panic_abort

# wasm-pack creates a .gitignore which will stop this from being deployed to gh-pages
rm `pwd`/web/pkg/.gitignore
