#!/usr/bin/env bash

set -e

echo Cleaning flutter
flutter clean

echo Cleaning web/pkg
rm -rf web/pkg

echo Cleaning Rust
(cd native && cargo clean)

echo Cleaning Generated code
rm -f ios/Runner/bridge_generated.h \
   lib/bridge_definitions.dart \
   lib/bridge_generated.dart \
   lib/bridge_generated.io.dart \
   lib/bridge_generated.web.dart \
   macos/Runner/bridge_generated.h \
   native/src/bridge_generated.io.rs \
   native/src/bridge_generated.rs \
   native/src/bridge_generated.web.rs
